// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Onion.Infrastructure.SqlServerDb.Services;

namespace Onion.UI.WebApi.Migrations
{
    [DbContext(typeof(SqlServerStudentsDbContext))]
    [Migration("20200320163316_Student_StudentGroup")]
    partial class Student_StudentGroup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Onion.Domain.Entities.Student", b =>
                {
                    b.Property<int>("IdStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentGroupIdStudentGroup")
                        .HasColumnType("int");

                    b.HasKey("IdStudent");

                    b.HasIndex("StudentGroupIdStudentGroup");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Onion.Domain.Entities.StudentGroup", b =>
                {
                    b.Property<int>("IdStudentGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdStudentGroup");

                    b.ToTable("StudentsGroups");
                });

            modelBuilder.Entity("Onion.Domain.Entities.Student", b =>
                {
                    b.HasOne("Onion.Domain.Entities.StudentGroup", "StudentGroup")
                        .WithMany("Students")
                        .HasForeignKey("StudentGroupIdStudentGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
